settings:
  title: 'LxnChan's Status Page'
  url: 'https://lxnchan.cn' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 45 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
#  - id: blogMain
#    name: workers.cloudflare.com
#    description: 'You write code. They handle the rest.' # default=empty
#    url: 'https://workers.cloudflare.com/' # URL to fetch
#    method: GET # default=GET
#    expectStatus: 200 # operational status, default=200
#    followRedirect: false # should fetch follow redirects, default=false
#    linkable: false # allows the title to be a link, default=true

  - id: blogMain
    name: LxnChan's Blog
    description: 'My blog.'
    url: 'https://lxnchan.cn'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: 115Wiki
    name: 115Wiki
    url: 'https://115.anavi.cn/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: enderchest
    name: Cloud Drive - EnderChest
    url: 'https://enderchest.anavi.cn/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: fallbackA
    name: Baidu
    url: 'https://www.baidu.com/'
    method: GET
    expectStatus: 200
    linkable: false

  - id: fallbackB
    name: Google
    url: 'https://www.google.co.jp/'
    method: GET
    expectStatus: 200
    linkable: false
